services:
  db:
    image: postgres:14.2-alpine
    container_name: cpt-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cpt
      - POSTGRES_USER=cpt
      - POSTGRES_PASSWORD=cpt
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2-alpine
    container_name: cpt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  api:
    container_name: cpt-api
    build:
      context: ../api
      dockerfile: ../docker/dev.api.Dockerfile
    command: "./bin/dev -b 0.0.0.0"
    env_file:
      - ../api/.env.development
    environment:
      - RAILS_ENV=development
    volumes:
      - ../api:/api
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/dev.frontend.Dockerfile
    container_name: cpt-frontend
    env_file:
      - ../frontend/.env.development
    volumes:
      - ../frontend:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: {}
  redis_data: {}